### PR TITLE
first cut about lab

### PR DESCRIPTION
**Pull request by niallrobinson**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Copy looks good. How a about a screenshot of the page?

**Comment by niallrobinson** [comment]
What - you mean so you don't have to pull it down to look at it? Can do

**Comment by niallrobinson** [comment]
image

**Comment by jacobtomlinson** [comment]
That bottom margin looks pretty big. Can you reduce to to make half?

**Comment by jacobtomlinson** [comment]
@niallrobinson I'd like to merge this. Don't worry about the padding, but can you fix the conflict please.

**Pull request merged**
