### PR TITLE
Updated mugshots and changed affiliation details

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Affiliations are now static and do not change if a person leaves the team. Currently used affiliation values are `core`, `intern` and `mascot`.

There is also a new value for the profiles called `current` which is a boolean representing if someone currently works in the lab.

I've also updates mugshot urls to be absolute and not relative to a magic prefix. 

The new mugshots have been updated.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Waiting on #350

**Comment by jacobtomlinson** [comment]
image

**Comment by jacobtomlinson** [comment]
image

**Comment by jacobtomlinson** [comment]
@05tb Could you have a look at this and make sure it looks sensible.

**Comment by 05tb** [comment]
Everything look sensible however there is an issue.
Upon clicking the team members page their image does not load at the top of the page.
The reason for this is the image url is being appended to another url, see code below. 
```
background-image: url(http://s3-eu-west-1.amazonaws.com/informatics-webimages/https://images.informaticslab.co.uk/profiles/cropped/alberto-arribas.png);
```
Feel like this is due to the removal `of relative to a magic prefix` image link method and swap to absolute urls

**Comment by 05tb** [comment]
Raised as issue #351

**Comment by jacobtomlinson** [comment]
Thanks! In future don't worry about raising issues against PRs. Just put the issue in a comment on the PR.

**Comment by 05tb** [comment]
Okay will do :) 

I was also just about to push this change but you beat me to it!

**Pull request merged**
