### PR TITLE
Add Trello projects to the main page

### PR DESCRIPTION
**Pull request by jacobtomlinson**
image

### CODE REVIEW

**Comment by tam203** [comment]
Does this expose the content or just the titles of the cards?

**Comment by jacobtomlinson** [comment]
@tam203 Just the titles, intentionally.

**Comment by niallrobinson** [comment]
@jacobtomlinson I think we need to different between the projects we are working on now (trello cards) and the more substantial project descriptions below. How about we leave the projects as projects and call the trello cards, "what we're working on this week" or something. They aren't really full blooded Projects, but different sprinty type things

**Comment by jacobtomlinson** [comment]
I agree. I'll add some headers.

I was also thinking we could even take this one step further and convert the projects into Trello cards on the completed list. Then the whole section would be dynamic and update as we move cards around. Just a thought.

**Pull request merged**
