### PR TITLE
Rhino Blog and Project pages

### PR DESCRIPTION
**Pull request by 05tb**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
The content looks good! Worth going over again as there were a few spelling mistakes. I'll also wait for @RossJM to give it a read before merging it.

**Comment by jacobtomlinson** [comment]
Also we've been discussing putting all project content into the project pages and not writing blog posts about it. Maybe it's worth merging the two together.

**Comment by 05tb** [comment]
I have fixed the spelling mistake!
Will go through it with @RossJM  and also ask him about the blog/project merge plans

**Comment by 05tb** [comment]
@RossJM has checked over the blog post and we are going to remove the project overview from this.

The project page will stay and Ross is going to edit this to better reflect the reason for the project.

**Pull request merged**
